# Generated by Django 4.1.4 on 2022-12-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_name_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='United States', max_length=20, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dateofbirth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='dateofbirth'),
        ),
    ]
